language: node_js
os:
  - "linux"
node_js:
  - "10"
cache: npm

notifications:
  email:
    recipients:
      - renkeju@gmail.com
    on_success: change
    on_failure: always

install:
  - npm install -g gitbook-cli
  - gitbook install

script:
  - gitbook build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep_history: true
  on:
    branch: master
  local_dir: _book
  name: Deployment Bot
  email: renkeju@gmail.com
  allow_empty_commit: false
